---
- name: JBoss cli
  hosts: localhost
  tasks:
    
  - name: Validate if jboss is UP
    tags: jbossvalidate
    wait_for:
      host: "localhost"
      port: 8080
      delay: 10
      timeout: 30
      state: started
      msg: "JBoss server is not running"

  - name: Jboss get log level
    shell: "{{jboss_home}}/bin/jboss-cli.sh --connect --commands='/subsystem=logging/root-logger=ROOT:change-root-log-level(level={{log_level}})' > out.txt"
    register: lsout
    tags: lsout 
  
  - name: Display the file
    shell: cat out.txt
    register: displaylist

  - debug: msg="{{displaylist.stdout_lines}}"